# Generated by Django 5.2.5 on 2025-11-03 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Correo electrónico del usuario', max_length=254, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del usuario', max_length=100)),
                ('apellido', models.CharField(help_text='Apellido del usuario', max_length=100)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('VETERINARIO', 'Veterinario'), ('RECEPCIONISTA', 'Recepcionista')], default='RECEPCIONISTA', help_text='Rol del usuario en el sistema', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la mascota', max_length=100)),
                ('especie', models.CharField(choices=[('CANINO', 'Perro'), ('FELINO', 'Gato'), ('AVE', 'Ave'), ('ROEDOR', 'Roedor'), ('REPTIL', 'Reptil'), ('OTRO', 'Otro')], help_text='Especie de la mascota', max_length=20)),
                ('raza', models.CharField(blank=True, help_text='Raza de la mascota (opcional)', max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], default='M', help_text='Sexo de la mascota', max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento de la mascota', null=True)),
                ('color', models.CharField(blank=True, help_text='Color de la mascota', max_length=50)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kilogramos', max_digits=5, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones generales (alergias, condiciones especiales, etc.)')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el paciente está activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del tutor (dueño)', max_length=100)),
                ('apellido', models.CharField(help_text='Apellido del tutor', max_length=100)),
                ('rut', models.CharField(help_text='RUT sin puntos, con guión. Ej: 12345678-9', max_length=12, unique=True)),
                ('telefono', models.CharField(help_text='Teléfono de contacto', max_length=15)),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico (opcional)', max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, help_text='Dirección del tutor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('usuario', models.OneToOneField(help_text='Usuario asociado al veterinario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rut', models.CharField(help_text='RUT sin puntos, con guión. Ej: 12345678-9', max_length=12, unique=True)),
                ('especialidad', models.CharField(blank=True, help_text='Especialidad del veterinario. Ej: Cirugía, Medicina Interna', max_length=100)),
                ('telefono', models.CharField(help_text='Teléfono del veterinario. Ej: +56912345678', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(help_text='Fecha y hora de la cita')),
                ('motivo_consulta', models.TextField(help_text='Motivo de la consulta')),
                ('estado', models.CharField(choices=[('AGENDADA', 'Agendada'), ('CONFIRMADA', 'Confirmada'), ('EN_CURSO', 'En Curso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No Asistió')], default='AGENDADA', help_text='Estado actual de la cita', max_length=20)),
                ('notas_recepcion', models.TextField(blank=True, help_text='Notas adicionales del recepcionista')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(help_text='Mascota que será atendida', on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
                ('veterinario', models.ForeignKey(help_text='Veterinario que atenderá la cita', on_delete=django.db.models.deletion.PROTECT, to='core.veterinario')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='tutor',
            field=models.ForeignKey(help_text='Tutor (dueño) de la mascota', on_delete=django.db.models.deletion.CASCADE, to='core.tutor'),
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateTimeField(help_text='Fecha y hora de la atención')),
                ('motivo', models.TextField(help_text='Motivo de la consulta')),
                ('diagnostico', models.TextField(help_text='Diagnóstico médico')),
                ('tratamiento', models.TextField(help_text='Tratamiento prescrito')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales del veterinario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cita', models.OneToOneField(blank=True, help_text='Cita asociada (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cita')),
                ('paciente', models.ForeignKey(help_text='Mascota del historial', on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
                ('veterinario', models.ForeignKey(help_text='Veterinario que realizó la atención', on_delete=django.db.models.deletion.PROTECT, to='core.veterinario')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Día de la semana para este bloque')),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio del bloque')),
                ('hora_fin', models.TimeField(help_text='Hora de fin del bloque')),
                ('veterinario', models.ForeignKey(help_text='Veterinario al que pertenece este bloque de horario', on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.veterinario')),
            ],
            options={
                'ordering': ['veterinario', 'dia_semana', 'hora_inicio'],
                'unique_together': {('veterinario', 'dia_semana', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
