# Generated by Django 5.2.5 on 2025-11-03 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('SOLICITADA', 'Solicitada por Veterinario'), ('AGENDADA', 'Agendada'), ('CONFIRMADA', 'Confirmada'), ('EN_CURSO', 'En Curso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No Asistió')], default='AGENDADA', help_text='Estado actual de la cita', max_length=20),
        ),
    ]
