# Generated by Django 5.2.5 on 2025-12-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cita_creada_por_alter_cita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Monto total de la consulta', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='observaciones_veterinario',
            field=models.TextField(blank=True, help_text='Observaciones y resumen de la atención por parte del veterinario'),
        ),
        migrations.AddField(
            model_name='cita',
            name='tipo_pago',
            field=models.CharField(blank=True, choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('EFECTIVO', 'Efectivo')], help_text='Tipo de pago realizado', max_length=20, null=True),
        ),
    ]
