# Generated by Django 5.2.5 on 2025-12-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cita_monto_cita_observaciones_veterinario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('SOLICITADA', 'Solicitada por Veterinario'), ('AGENDADA', 'Agendada'), ('CONFIRMADA', 'Confirmada'), ('EN_CURSO', 'En Curso'), ('REALIZADO', 'Realizado'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No Asistió')], default='AGENDADA', help_text='Estado actual de la cita', max_length=20),
        ),
    ]
