# Generated by Django 5.2.5 on 2025-12-09 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cita_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ALERGIA', 'Alergia'), ('CONDICION_CRONICA', 'Condición Crónica'), ('MEDICAMENTO_PROHIBIDO', 'Medicamento Prohibido'), ('OTRO', 'Otro')], default='ALERGIA', help_text='Tipo de condición', max_length=30)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la alergia o condición')),
                ('severidad', models.CharField(choices=[('LEVE', 'Leve'), ('MODERADA', 'Moderada'), ('GRAVE', 'Grave')], default='MODERADA', help_text='Nivel de severidad', max_length=15)),
                ('fecha_deteccion', models.DateField(help_text='Fecha en que se detectó la condición')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la condición sigue activa')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(help_text='Mascota con la condición/alergia', on_delete=django.db.models.deletion.CASCADE, related_name='alergias', to='core.paciente')),
            ],
            options={
                'verbose_name': 'Alergia/Condición',
                'verbose_name_plural': 'Alergias/Condiciones',
                'ordering': ['-activa', '-severidad', '-fecha_deteccion'],
            },
        ),
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cirugia', models.CharField(help_text='Tipo de cirugía (ej: Esterilización, Extracción dental, Cesárea)', max_length=150)),
                ('fecha_cirugia', models.DateField(help_text='Fecha en que se realizó la cirugía')),
                ('descripcion', models.TextField(help_text='Descripción detallada del procedimiento')),
                ('complicaciones', models.TextField(blank=True, help_text='Complicaciones observadas durante o después de la cirugía')),
                ('costo', models.DecimalField(decimal_places=0, help_text='Costo de la cirugía', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(help_text='Mascota operada', on_delete=django.db.models.deletion.CASCADE, related_name='cirugias', to='core.paciente')),
                ('veterinario', models.ForeignKey(help_text='Veterinario que realizó la cirugía', on_delete=django.db.models.deletion.PROTECT, to='core.veterinario')),
            ],
            options={
                'verbose_name': 'Cirugía',
                'verbose_name_plural': 'Cirugías',
                'ordering': ['-fecha_cirugia'],
            },
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vacuna', models.CharField(help_text='Nombre de la vacuna (ej: Rabia, Parvovirus, Triple Felina)', max_length=100)),
                ('fecha_aplicacion', models.DateField(help_text='Fecha en que se aplicó la vacuna')),
                ('proxima_dosis', models.DateField(blank=True, help_text='Fecha programada para la próxima dosis (si aplica)', null=True)),
                ('lote', models.CharField(blank=True, help_text='Número de lote de la vacuna', max_length=50)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre la vacunación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(help_text='Mascota vacunada', on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='core.paciente')),
                ('veterinario', models.ForeignKey(help_text='Veterinario que aplicó la vacuna', on_delete=django.db.models.deletion.PROTECT, to='core.veterinario')),
            ],
            options={
                'verbose_name': 'Vacuna',
                'verbose_name_plural': 'Vacunas',
                'ordering': ['-fecha_aplicacion'],
            },
        ),
    ]
