# Generated by Django 5.2.5 on 2025-12-09 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alergia_cirugia_vacuna'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=0, help_text='Monto total a pagar', max_digits=10)),
                ('monto_pagado', models.DecimalField(decimal_places=0, default=0, help_text='Monto ya pagado', max_digits=10)),
                ('saldo_pendiente', models.DecimalField(decimal_places=0, help_text='Saldo restante', max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago Parcial'), ('PAGADO', 'Pagado')], default='PENDIENTE', help_text='Estado del pago', max_length=20)),
                ('metodo_pago_principal', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('TRANSFERENCIA', 'Transferencia')], help_text='Método de pago principal', max_length=20, null=True)),
                ('fecha_pago_completo', models.DateTimeField(blank=True, help_text='Fecha en que se completó el pago', null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el pago')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cita', models.OneToOneField(help_text='Cita asociada al pago', on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='core.cita')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=0, help_text='Monto del abono', max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('TRANSFERENCIA', 'Transferencia')], help_text='Método de pago utilizado', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha del abono')),
                ('notas', models.TextField(blank=True, help_text='Notas sobre este abono')),
                ('registrado_por', models.ForeignKey(help_text='Usuario que registró el abono', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonos_registrados', to=settings.AUTH_USER_MODEL)),
                ('pago', models.ForeignKey(help_text='Pago al que pertenece este abono', on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='core.pago')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
